<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="sv_SE">
<context>
    <name>CTCron</name>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="109"/>
        <source>No password entry found for uid &apos;%1&apos;</source>
        <translation>Ingen lösenordspost hittades för uid &quot;%1&quot;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="246"/>
        <source>File generated by Crontablib the %1.</source>
        <comment>Generation Message + current date</comment>
        <translation>Fil genererad av Crontablib %1.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="286"/>
        <source>&lt;em&gt;No output.&lt;/em&gt;</source>
        <translation>&lt;em&gt;Ingen utdata.&lt;/em&gt;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="292"/>
        <source>&lt;em&gt;No error.&lt;/em&gt;</source>
        <translation>&lt;em&gt;Inget fel.&lt;/em&gt;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="298"/>
        <source>&lt;p&gt;&lt;strong&gt;Command:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Command could not be started&lt;/strong&gt;</source>
        <translation>&lt;p&gt;&lt;strong&gt;Kommando:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Kommandot kunde inte startas&lt;/strong&gt;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="302"/>
        <source>&lt;p&gt;&lt;strong&gt;Command:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Standard Output :&lt;/strong&gt;&lt;pre&gt;%2&lt;/pre&gt;&lt;strong&gt;Error Output :&lt;/strong&gt;&lt;pre&gt;%3&lt;/pre&gt;</source>
        <translation>&lt;p&gt;&lt;strong&gt;Kommando:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Standardutdata:&lt;/strong&gt;&lt;pre&gt;%2&lt;/pre&gt;&lt;strong&gt;Fel utdata:&lt;/strong&gt;&lt;pre&gt;%3&lt;/pre&gt;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="309"/>
        <source>An error occurred while updating crontab.</source>
        <translation>Ett fel inträffade vid uppdatering av crontab.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="318"/>
        <source>Unable to open crontab file for writing</source>
        <translation>Kunde inte öppna crontab-filen för skrivning</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="319"/>
        <source>The file %1 could not be opened.</source>
        <translation>Filen %1 kunde inte öppnas.</translation>
    </message>
</context>
<context>
    <name>CTDayOfMonth</name>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="22"/>
        <source>every day </source>
        <translation>Varje dag </translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>1st</source>
        <translation>1:a</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>2nd</source>
        <translation>2:a</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>3rd</source>
        <translation>3:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>4th</source>
        <translation>4:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>5th</source>
        <translation>5:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>6th</source>
        <translation>6:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>7th</source>
        <translation>7:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>8th</source>
        <translation>8:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>9th</source>
        <translation>9:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>10th</source>
        <translation>10:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>11th</source>
        <translation>11:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>12th</source>
        <translation>12:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>13th</source>
        <translation>13:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>14th</source>
        <translation>14:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>15th</source>
        <translation>15:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>16th</source>
        <translation>16:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>17th</source>
        <translation>17:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>18th</source>
        <translation>18:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>19th</source>
        <translation>19:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>20th</source>
        <translation>20:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>21st</source>
        <translation>21:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>22nd</source>
        <translation>22:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>23rd</source>
        <translation>23:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>24th</source>
        <translation>24:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>25th</source>
        <translation>25:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>26th</source>
        <translation>26:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>27th</source>
        <translation>27:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>28th</source>
        <translation>28:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>29th</source>
        <translation>29:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>30th</source>
        <translation>30:e</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>31st</source>
        <translation>31:e</translation>
    </message>
</context>
<context>
    <name>CTDayOfWeek</name>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="43"/>
        <source>every day </source>
        <translation>Varje dag </translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Mon</source>
        <translation>Mån</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Tue</source>
        <translation>Tis</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Wed</source>
        <translation>Ons</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Thu</source>
        <translation>Tor</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Fri</source>
        <translation>Fre</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Sat</source>
        <translation>Lör</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Sun</source>
        <translation>Sön</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Monday</source>
        <translation>Måndag</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Tuesday</source>
        <translation>Tisdag</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Wednesday</source>
        <translation>Onsdag</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Thursday</source>
        <translation>Torsdag</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Friday</source>
        <translation>Fredag</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Saturday</source>
        <translation>Lördag</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Sunday</source>
        <translation>Söndag</translation>
    </message>
</context>
<context>
    <name>CTGlobalCron</name>
    <message>
        <location filename="../crontablib/ctGlobalCron.cpp" line="28"/>
        <source>All users</source>
        <translation>Alla användare</translation>
    </message>
</context>
<context>
    <name>CTHost</name>
    <message>
        <location filename="../crontablib/cthost.cpp" line="59"/>
        <source>You have been blocked from using Crontablib                          by either the /etc/cron.allow file or the /etc/cron.deny file.                          

Check the crontab man page for further details.</source>
        <translation>Du har blockerats från att använda Crontablib                          av endera filerna /etc/cron.allow, eller /etc/cron.deny.                          

Kolla crontab man page för vidare detaljer.</translation>
    </message>
    <message>
        <location filename="../crontablib/cthost.cpp" line="141"/>
        <source>User %1: %2</source>
        <comment>User login: errorMessage</comment>
        <translation>Användare %1: %2</translation>
    </message>
</context>
<context>
    <name>CTMonth</name>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="22"/>
        <source>every month</source>
        <translation>Varje månad</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>January</source>
        <translation>Januari</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>February</source>
        <translation>Februari</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>March</source>
        <translation>Mars</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>April</source>
        <translation>April</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>May</source>
        <comment>May long</comment>
        <translation>Maj</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>June</source>
        <translation>Juni</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>July</source>
        <comment>July long</comment>
        <translation>Juli</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>August</source>
        <translation>Augusti</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>September</source>
        <translation>September</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>October</source>
        <translation>Oktober</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>November</source>
        <translation>November</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>December</source>
        <translation>December</translation>
    </message>
</context>
<context>
    <name>CTSystemCron</name>
    <message>
        <location filename="../crontablib/ctSystemCron.cpp" line="45"/>
        <source>System Crontab</source>
        <translation>Systemets Crontab</translation>
    </message>
</context>
<context>
    <name>CTTask</name>
    <message>
        <location filename="../crontablib/cttask.cpp" line="232"/>
        <source>at system startup</source>
        <translation>vid systemstart</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="239"/>
        <source>%1, %2</source>
        <comment>1:Time Description, 2:Date Description</comment>
        <translation>%1, %2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="244"/>
        <source>every %1</source>
        <comment>Every &apos;days of week&apos;</comment>
        <translation>Varje %1</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="248"/>
        <source>%1 of %2</source>
        <comment>&apos;Days of month&apos; of &apos;Months&apos;</comment>
        <translation>%1 av %2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="261"/>
        <source>every day </source>
        <translation>Varje dag </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="272"/>
        <source>%1 as well as %2</source>
        <comment>1:Day of month, 2:Day of week</comment>
        <translation>%1 liksom %2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="304"/>
        <source>%1:%2</source>
        <comment>1:Hour, 2:Minute</comment>
        <translation>%1:%2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="314"/>
        <source>, and </source>
        <translation>, och </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="316"/>
        <source> and </source>
        <translation> och </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="319"/>
        <source>, </source>
        <translation>, </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="325"/>
        <source>at %1</source>
        <comment>Hour::Minute list</comment>
        <translation>%1</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="332"/>
        <source>Every minute</source>
        <comment>Every minute</comment>
        <translation>Varje minut</translation>
    </message>
</context>
<context>
    <name>CTUnit</name>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="170"/>
        <source>,</source>
        <translation>,</translation>
    </message>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="171"/>
        <source> and </source>
        <translation> och </translation>
    </message>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="174"/>
        <source>, </source>
        <translation>, </translation>
    </message>
</context>
<context>
    <name>CTVariable</name>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="121"/>
        <source>Override default home folder.</source>
        <translation>Åsidosätt standardhemkatalog.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="124"/>
        <source>Email output to specified account.</source>
        <translation>Mejla utdata till specificerat mejlkonto.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="127"/>
        <source>Override default shell.</source>
        <translation>Åsidosätt standardskal.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="130"/>
        <source>Folders to search for program files.</source>
        <translation>Mappar att genomsöka för programfiler.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="133"/>
        <source>Dynamic libraries location.</source>
        <translation>Plats för dynamiska bibliotek.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="136"/>
        <source>Local Variable</source>
        <translation>Lokal variabel</translation>
    </message>
</context>
</TS>
