<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="be_BY">
<context>
    <name>CTCron</name>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="109"/>
        <source>No password entry found for uid &apos;%1&apos;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="246"/>
        <source>File generated by Crontablib the %1.</source>
        <comment>Generation Message + current date</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="286"/>
        <source>&lt;em&gt;No output.&lt;/em&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="292"/>
        <source>&lt;em&gt;No error.&lt;/em&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="298"/>
        <source>&lt;p&gt;&lt;strong&gt;Command:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Command could not be started&lt;/strong&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="302"/>
        <source>&lt;p&gt;&lt;strong&gt;Command:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Standard Output :&lt;/strong&gt;&lt;pre&gt;%2&lt;/pre&gt;&lt;strong&gt;Error Output :&lt;/strong&gt;&lt;pre&gt;%3&lt;/pre&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="309"/>
        <source>An error occurred while updating crontab.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="318"/>
        <source>Unable to open crontab file for writing</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="319"/>
        <source>The file %1 could not be opened.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CTDayOfMonth</name>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="22"/>
        <source>every day </source>
        <translation>кожны дзень </translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>1st</source>
        <translation>1га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>2nd</source>
        <translation>2га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>3rd</source>
        <translation>3га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>4th</source>
        <translation>4га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>5th</source>
        <translation>5га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>6th</source>
        <translation>6га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>7th</source>
        <translation>7га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>8th</source>
        <translation>8га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>9th</source>
        <translation>9га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>10th</source>
        <translation>10га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>11th</source>
        <translation>11га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>12th</source>
        <translation>12га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>13th</source>
        <translation>13га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>14th</source>
        <translation>14га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>15th</source>
        <translation>15га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>16th</source>
        <translation>16га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>17th</source>
        <translation>17га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>18th</source>
        <translation>18га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>19th</source>
        <translation>19га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>20th</source>
        <translation>20га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>21st</source>
        <translation>21га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>22nd</source>
        <translation>22га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>23rd</source>
        <translation>23га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>24th</source>
        <translation>24га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>25th</source>
        <translation>25га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>26th</source>
        <translation>26га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>27th</source>
        <translation>27га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>28th</source>
        <translation>28га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>29th</source>
        <translation>29га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>30th</source>
        <translation>30га</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>31st</source>
        <translation>31га</translation>
    </message>
</context>
<context>
    <name>CTDayOfWeek</name>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="43"/>
        <source>every day </source>
        <translation>кожны дзень </translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Mon</source>
        <translation>Пн</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Tue</source>
        <translation>Аў</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Wed</source>
        <translation>Ср</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Thu</source>
        <translation>Чц</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Fri</source>
        <translation>Пт</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Sat</source>
        <translation>Сб</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Sun</source>
        <translation>Нд</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Monday</source>
        <translation>Панядзелак</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Tuesday</source>
        <translation>Аўторак</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Wednesday</source>
        <translation>Серада</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Thursday</source>
        <translation>Чацьвер</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Friday</source>
        <translation>Пятніца</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Saturday</source>
        <translation>Субота</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Sunday</source>
        <translation>Нядзеля</translation>
    </message>
</context>
<context>
    <name>CTGlobalCron</name>
    <message>
        <location filename="../crontablib/ctGlobalCron.cpp" line="28"/>
        <source>All users</source>
        <translation>Усе карыстальнікі</translation>
    </message>
</context>
<context>
    <name>CTHost</name>
    <message>
        <location filename="../crontablib/cthost.cpp" line="59"/>
        <source>You have been blocked from using Crontablib                          by either the /etc/cron.allow file or the /etc/cron.deny file.                          

Check the crontab man page for further details.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cthost.cpp" line="141"/>
        <source>User %1: %2</source>
        <comment>User login: errorMessage</comment>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CTMonth</name>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="22"/>
        <source>every month</source>
        <translation>кожны месяц</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>January</source>
        <translation>Студзеня</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>February</source>
        <translation>Лютага</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>March</source>
        <translation>Сакавіка</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>April</source>
        <translation>Красавіка</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>May</source>
        <comment>May long</comment>
        <translation>Траўня</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>June</source>
        <translation>Чэрвеня</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>July</source>
        <comment>July long</comment>
        <translation>Ліпеня</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>August</source>
        <translation>Жніўня</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>September</source>
        <translation>Верасня</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>October</source>
        <translation>Кастрычніка</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>November</source>
        <translation>Лістапада</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>December</source>
        <translation>Снежня</translation>
    </message>
</context>
<context>
    <name>CTSystemCron</name>
    <message>
        <location filename="../crontablib/ctSystemCron.cpp" line="45"/>
        <source>System Crontab</source>
        <translation>Сістэмны Crontab</translation>
    </message>
</context>
<context>
    <name>CTTask</name>
    <message>
        <location filename="../crontablib/cttask.cpp" line="232"/>
        <source>at system startup</source>
        <translation>Пры запуску сістэмы</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="239"/>
        <source>%1, %2</source>
        <comment>1:Time Description, 2:Date Description</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="244"/>
        <source>every %1</source>
        <comment>Every &apos;days of week&apos;</comment>
        <translation>Па %1</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="248"/>
        <source>%1 of %2</source>
        <comment>&apos;Days of month&apos; of &apos;Months&apos;</comment>
        <translation>%1 %2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="261"/>
        <source>every day </source>
        <translation>кожны дзень </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="272"/>
        <source>%1 as well as %2</source>
        <comment>1:Day of month, 2:Day of week</comment>
        <translation>%1 пры гэтым %2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="304"/>
        <source>%1:%2</source>
        <comment>1:Hour, 2:Minute</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="314"/>
        <source>, and </source>
        <translation>, і </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="316"/>
        <source> and </source>
        <translation> і </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="319"/>
        <source>, </source>
        <translation></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="325"/>
        <source>at %1</source>
        <comment>Hour::Minute list</comment>
        <translation>у %1</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="332"/>
        <source>Every minute</source>
        <comment>Every minute</comment>
        <translation>кожную хвіліну</translation>
    </message>
</context>
<context>
    <name>CTUnit</name>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="170"/>
        <source>,</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="171"/>
        <source> and </source>
        <translation> і </translation>
    </message>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="174"/>
        <source>, </source>
        <translation></translation>
    </message>
</context>
<context>
    <name>CTVariable</name>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="121"/>
        <source>Override default home folder.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="124"/>
        <source>Email output to specified account.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="127"/>
        <source>Override default shell.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="130"/>
        <source>Folders to search for program files.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="133"/>
        <source>Dynamic libraries location.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="136"/>
        <source>Local Variable</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
