<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ru_RU">
<context>
    <name>AboutDialog</name>
    <message>
        <location filename="../src/aboutdialog.ui" line="35"/>
        <source>About Zeit</source>
        <translation>О программе Zeit</translation>
    </message>
    <message>
        <location filename="../src/aboutdialog.ui" line="71"/>
        <source>about&amp;Qt</source>
        <translation>O библиотеке &amp;Qt</translation>
    </message>
</context>
<context>
    <name>AlarmDialog</name>
    <message>
        <location filename="../src/alarmdialog.ui" line="14"/>
        <source>Dialog</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="28"/>
        <source>Description:</source>
        <translation>Описание:</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="48"/>
        <source>Player:</source>
        <translation>Плеер:</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="58"/>
        <location filename="../src/alarmdialog.ui" line="85"/>
        <source>...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="75"/>
        <source>Sound File:</source>
        <translation>Зв. файл:</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="108"/>
        <source>Run at</source>
        <translation>Запустить в</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="115"/>
        <source> hr</source>
        <translation>час</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="125"/>
        <source> min</source>
        <translation>мин</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="139"/>
        <source>Mon</source>
        <translation>Пн</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="146"/>
        <source>Tue</source>
        <translation>Вт</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="153"/>
        <source>Wed</source>
        <translation>Ср</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="160"/>
        <source>Thu</source>
        <translation>Чт</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="167"/>
        <source>Fri</source>
        <translation>Пт</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="174"/>
        <source>Sat</source>
        <translation>Сб</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="181"/>
        <source>Sun</source>
        <translation>Вс</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.cpp" line="33"/>
        <location filename="../src/alarmdialog.cpp" line="40"/>
        <source>New Alarm</source>
        <translation>Новый будильник</translation>
    </message>
</context>
<context>
    <name>CTCron</name>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="100"/>
        <source>No password entry found for uid &apos;%1&apos;</source>
        <translation>Не введён пароль для uid &apos;%1&apos;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="237"/>
        <source>File generated by Crontablib the %1.</source>
        <comment>Generation Message + current date</comment>
        <translation>Файл создан при помощи Crontablib %1.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="275"/>
        <source>&lt;em&gt;No output.&lt;/em&gt;</source>
        <translation>&lt;em&gt;Нет выходных данных.&lt;/em&gt;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="281"/>
        <source>&lt;em&gt;No error.&lt;/em&gt;</source>
        <translation>&lt;em&gt;Нет ошибок.&lt;/em&gt;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="287"/>
        <source>&lt;p&gt;&lt;strong&gt;Command:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Command could not be started&lt;/strong&gt;</source>
        <translation>&lt;p&gt;&lt;strong&gt;Команда:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Команда не может быть запущена&lt;/strong&gt;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="289"/>
        <source>&lt;p&gt;&lt;strong&gt;Command:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Standard Output :&lt;/strong&gt;&lt;pre&gt;%2&lt;/pre&gt;&lt;strong&gt;Error Output :&lt;/strong&gt;&lt;pre&gt;%3&lt;/pre&gt;</source>
        <translation>&lt;p&gt;&lt;strong&gt;Команда:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Стандартный вывод :&lt;/strong&gt;&lt;pre&gt;%2&lt;/pre&gt;&lt;strong&gt;Вывод ошибок :&lt;/strong&gt;&lt;pre&gt;%3&lt;/pre&gt;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="291"/>
        <source>An error occurred while updating crontab.</source>
        <translation>Произошла ошибка при перезаписи crontab.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="298"/>
        <source>Unable to open crontab file for writing</source>
        <translation>Невозможно открыть crontab для записи</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="298"/>
        <source>The file %1 could not be opened.</source>
        <translation>Невозможно открыть файл %1.</translation>
    </message>
</context>
<context>
    <name>CTDayOfMonth</name>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="22"/>
        <source>every day </source>
        <translation>каждый день </translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>1st</source>
        <translation>1го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>2nd</source>
        <translation>2го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>3rd</source>
        <translation>3го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>4th</source>
        <translation>4го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>5th</source>
        <translation>5го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>6th</source>
        <translation>6го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>7th</source>
        <translation>7го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>8th</source>
        <translation>8го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>9th</source>
        <translation>9го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>10th</source>
        <translation>10го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>11th</source>
        <translation>11го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>12th</source>
        <translation>12го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>13th</source>
        <translation>13го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>14th</source>
        <translation>14го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>15th</source>
        <translation>15го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>16th</source>
        <translation>16го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>17th</source>
        <translation>17го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>18th</source>
        <translation>18го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>19th</source>
        <translation>19го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>20th</source>
        <translation>20го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>21st</source>
        <translation>21го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>22nd</source>
        <translation>22го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>23rd</source>
        <translation>23го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>24th</source>
        <translation>24го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>25th</source>
        <translation>25го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>26th</source>
        <translation>26го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>27th</source>
        <translation>27го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>28th</source>
        <translation>28го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>29th</source>
        <translation>29го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>30th</source>
        <translation>30го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>31st</source>
        <translation>31го</translation>
    </message>
</context>
<context>
    <name>CTDayOfWeek</name>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="43"/>
        <source>every day </source>
        <translation>каждый день </translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Mon</source>
        <translation>Пн</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Tue</source>
        <translation>Вт</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Wed</source>
        <translation>Ср</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Thu</source>
        <translation>Чт</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Fri</source>
        <translation>Пт</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Sat</source>
        <translation>Сб</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Sun</source>
        <translation>Вс</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Monday</source>
        <translation>Понедельник</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Tuesday</source>
        <translation>Вторник</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Wednesday</source>
        <translation>Среда</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Thursday</source>
        <translation>Четверг</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Friday</source>
        <translation>Пятница</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Saturday</source>
        <translation>Суббота</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Sunday</source>
        <translation>Воскресенье</translation>
    </message>
</context>
<context>
    <name>CTGlobalCron</name>
    <message>
        <location filename="../crontablib/ctGlobalCron.cpp" line="28"/>
        <source>All users</source>
        <translation>Все пользователи</translation>
    </message>
</context>
<context>
    <name>CTHelper</name>
    <message>
        <location filename="../crontablib/ctHelper.cpp" line="20"/>
        <source>No comment</source>
        <translation>Нет комментария</translation>
    </message>
</context>
<context>
    <name>CTHost</name>
    <message>
        <location filename="../crontablib/cthost.cpp" line="57"/>
        <source>You have been blocked from using Crontablib	                      by either the /etc/cron.allow file or the /etc/cron.deny file.	                      

Check the crontab man page for further details.</source>
        <translation>Доступ к Crontablib был заблокирован \nпосредством одного из файлов  /etc/cron.allow или /etc/cron.deny.\n\nСмотрите crontab для более подробной информации.</translation>
    </message>
    <message>
        <location filename="../crontablib/cthost.cpp" line="139"/>
        <source>User %1: %2</source>
        <comment>User login: errorMessage</comment>
        <translation>Пользователь %1: %2</translation>
    </message>
</context>
<context>
    <name>CTMonth</name>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="22"/>
        <source>every month</source>
        <translation>каждом месяце</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>January</source>
        <translation>Январе</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>February</source>
        <translation>Феврале</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>March</source>
        <translation>Марте</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>April</source>
        <translation>Апреле</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>May</source>
        <comment>May long</comment>
        <translation>Мае</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>June</source>
        <translation>Июне</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>July</source>
        <comment>July long</comment>
        <translation>Июле</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>August</source>
        <translation>Августе</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>September</source>
        <translation>Сентябре</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>October</source>
        <translation>Октябре</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>November</source>
        <translation>Ноябре</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>December</source>
        <translation>Декабре</translation>
    </message>
</context>
<context>
    <name>CTSystemCron</name>
    <message>
        <location filename="../crontablib/ctSystemCron.cpp" line="45"/>
        <source>System Crontab</source>
        <translation>Системный Crontab</translation>
    </message>
</context>
<context>
    <name>CTTask</name>
    <message>
        <location filename="../crontablib/cttask.cpp" line="238"/>
        <source>At system startup</source>
        <translation>При старте системы</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="245"/>
        <source>%1, %2</source>
        <comment>1:Time Description, 2:Date Description</comment>
        <translation>%1, %2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="249"/>
        <source>every %1</source>
        <comment>Every &apos;days of week&apos;</comment>
        <translation>каждые %1</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="253"/>
        <source>%1 of %2</source>
        <comment>&apos;Days of month&apos; of &apos;Months&apos;</comment>
        <translation>%1 в %2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="264"/>
        <source>every day </source>
        <translation>каждый день </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="275"/>
        <source>%1 as well as %2</source>
        <comment>1:Day of month, 2:Day of week</comment>
        <translation>%1 к тому же %2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="305"/>
        <source>%1:%2</source>
        <comment>1:Hour, 2:Minute</comment>
        <translation>%1:%2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="314"/>
        <source>, and </source>
        <translation>, и </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="316"/>
        <source> and </source>
        <translation> и </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="319"/>
        <source>, </source>
        <translation>, </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="325"/>
        <source>At %1</source>
        <comment>Hour::Minute list</comment>
        <translation>В %1</translation>
    </message>
    <message numerus="yes">
        <location filename="../crontablib/cttask.cpp" line="332"/>
        <source>Every %L minute(s)</source>
        <comment>Every minute</comment>
        <translation>
            <numerusform>Каждую %n минуту</numerusform>
            <numerusform>Каждые %n минуты</numerusform>
            <numerusform>Каждые %n минут</numerusform>
        </translation>
    </message>
</context>
<context>
    <name>CTUnit</name>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="170"/>
        <source>,</source>
        <translation>,</translation>
    </message>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="171"/>
        <source> and </source>
        <translation> и </translation>
    </message>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="174"/>
        <source>, </source>
        <translation>, </translation>
    </message>
</context>
<context>
    <name>CTVariable</name>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="121"/>
        <source>Override default home folder.</source>
        <translation>Переопределить домашний каталог по умолчанию.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="124"/>
        <source>Email output to specified account.</source>
        <translation>Отправить электронное сообщение на указанный адрес.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="127"/>
        <source>Override default shell.</source>
        <translation>Переопределить командную оболочку по умолчанию.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="130"/>
        <source>Folders to search for program files.</source>
        <translation>Каталоги для поиска исполняемых файлов.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="133"/>
        <source>Dynamic libraries location.</source>
        <translation>Местоположение дианмических библиотек.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="136"/>
        <source>Local Variable</source>
        <translation>Локальная переменная</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="../src/mainwindow.ui" line="14"/>
        <source>Zeit</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="39"/>
        <source>&amp;Zeit</source>
        <translation>&amp;Приложение</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="49"/>
        <source>He&amp;lp</source>
        <translation>Помо&amp;щь</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="55"/>
        <source>Predefi&amp;ned</source>
        <translation>&amp;Шаблоны</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="75"/>
        <source>&amp;About</source>
        <translation>&amp;О Программе</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="80"/>
        <source>&amp;Add Task</source>
        <translation>&amp;Добавить задание</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="83"/>
        <source>Ctrl+A</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="88"/>
        <source>&amp;Quit</source>
        <translation>&amp;Выход</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="91"/>
        <source>Ctrl+Q</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="96"/>
        <source>&amp;Delete Task</source>
        <translation>&amp;Удалить задание</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="99"/>
        <source>Ctrl+D</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="104"/>
        <source>&amp;Modify Task</source>
        <translation>&amp;Изменить задание</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="107"/>
        <source>Ctrl+M</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="112"/>
        <source>&amp;Timer</source>
        <translation>&amp;Таймер</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="115"/>
        <source>Ctrl+T</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="120"/>
        <source>&amp;Alarm</source>
        <translation>&amp;Будильник</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="123"/>
        <source>Ctrl+L</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="51"/>
        <location filename="../src/mainwindow.cpp" line="147"/>
        <source>New Task</source>
        <translation>Новое задание</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="54"/>
        <source>Delete Task</source>
        <translation>Удалить задание</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="57"/>
        <source>Modify Task</source>
        <translation>Изменить задание</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="60"/>
        <source>New Alarm</source>
        <translation>Новый будильник</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="63"/>
        <source>New Timer</source>
        <translation>Новый таймер</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="154"/>
        <source>Deleting Task</source>
        <translation>Удаление задания</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="154"/>
        <source>Delete task?</source>
        <translation>Удалить задание?</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="165"/>
        <source>Edit Task</source>
        <translation>Изменить задание</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="../src/listitem.cpp" line="30"/>
        <source>Command</source>
        <translation>Команда</translation>
    </message>
    <message>
        <location filename="../src/listitem.cpp" line="31"/>
        <source>Description</source>
        <translation>Описание</translation>
    </message>
    <message>
        <location filename="../src/listitem.cpp" line="32"/>
        <source>Periodicity</source>
        <translation>Периодичность</translation>
    </message>
</context>
<context>
    <name>TaskDialog</name>
    <message>
        <location filename="../src/taskdialog.ui" line="14"/>
        <source>Dialog</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="28"/>
        <source>Description:</source>
        <translation>Описание:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="48"/>
        <source>Command:</source>
        <translation>Команда:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="60"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;b&gt;Time &amp;amp; Date:&lt;/b&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;b&gt;Время и дата:&lt;/b&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="75"/>
        <source>Basic</source>
        <translation>Базовый</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="87"/>
        <source>Ad&amp;vanced</source>
        <translation>&amp;Расширенный</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="102"/>
        <source>Minute:</source>
        <translation>Минуты:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="122"/>
        <source>Hour:</source>
        <translation>Часы:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="142"/>
        <source>Day:</source>
        <translation>Дни:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="162"/>
        <source>Weekday:</source>
        <translation>Дни недели:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="182"/>
        <source>Month:</source>
        <translation>Месяцы:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="36"/>
        <source>Every minute</source>
        <translation>Каждую минуту</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="36"/>
        <source>Every hour</source>
        <translation>Каждый час</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="36"/>
        <source>Every day</source>
        <translation>Каждый день</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="37"/>
        <source>Every week</source>
        <translation>Каждую неделю</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="37"/>
        <source>Every month</source>
        <translation>Каждый месяц</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="59"/>
        <source>Undefined</source>
        <translation>Без имени</translation>
    </message>
</context>
<context>
    <name>TimerDialog</name>
    <message>
        <location filename="../src/timerdialog.ui" line="14"/>
        <source>Dialog</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="28"/>
        <source>Description:</source>
        <translation>Описание:</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="48"/>
        <source>Player:</source>
        <translation>Плеер:</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="58"/>
        <location filename="../src/timerdialog.ui" line="85"/>
        <source>...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="75"/>
        <source>Sound file:</source>
        <translation>Зв. файл:</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="108"/>
        <source>Run at</source>
        <translation>Запустить в</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="115"/>
        <source> hrs</source>
        <translation>час</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="128"/>
        <source> mins</source>
        <translation>мин</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="141"/>
        <source>Now</source>
        <translation>Сейчас</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="148"/>
        <source>Reset</source>
        <translation>Сброс</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="159"/>
        <source>Show OSD notification</source>
        <translation>Показать экранное оповещение</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.cpp" line="32"/>
        <location filename="../src/timerdialog.cpp" line="34"/>
        <source>New Timer</source>
        <translation>Новый таймер</translation>
    </message>
</context>
</TS>
