<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ru_RU">
<context>
    <name>AboutDialog</name>
    <message>
        <location filename="../src/aboutdialog.cpp" line="31"/>
        <source>About Zeit</source>
        <translation>О программе Zeit</translation>
    </message>
    <message>
        <location filename="../src/aboutdialog.cpp" line="49"/>
        <source>About &amp;Qt</source>
        <translation>О &amp;Qt</translation>
    </message>
</context>
<context>
    <name>AlarmDialog</name>
    <message>
        <location filename="../src/alarmdialog.ui" line="14"/>
        <source>Dialog</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="20"/>
        <source>Description:</source>
        <translation>Описание:</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="34"/>
        <source>Player:</source>
        <translation>Плеер:</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="55"/>
        <source>Sound File:</source>
        <translation>Зв. файл:</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="76"/>
        <source>Run at</source>
        <translation>Запустить в</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="83"/>
        <source> hr</source>
        <translation>час</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="93"/>
        <source> min</source>
        <translation>мин</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="103"/>
        <source>Now</source>
        <translation>Сейчас</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="110"/>
        <source>Reset</source>
        <translation>Сброс</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="119"/>
        <source>Mon</source>
        <translation>Пн</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="126"/>
        <source>Tue</source>
        <translation>Вт</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="133"/>
        <source>Wed</source>
        <translation>Ср</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="140"/>
        <source>Thu</source>
        <translation>Чт</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="147"/>
        <source>Fri</source>
        <translation>Пт</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="154"/>
        <source>Sat</source>
        <translation>Сб</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.ui" line="161"/>
        <source>Sun</source>
        <translation>Вс</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.cpp" line="38"/>
        <location filename="../src/alarmdialog.cpp" line="45"/>
        <source>New Alarm</source>
        <translation>Новый будильник</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.cpp" line="101"/>
        <source>Player field should not be empty</source>
        <translation>Поле Плеер не должно быть пустым</translation>
    </message>
    <message>
        <location filename="../src/alarmdialog.cpp" line="105"/>
        <source>Soundfile field should not be empty</source>
        <translation>Поле Зв. файл не должно быть пустым</translation>
    </message>
</context>
<context>
    <name>CTCron</name>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="100"/>
        <source>No password entry found for uid &apos;%1&apos;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="237"/>
        <source>File generated by Crontablib the %1.</source>
        <comment>Generation Message + current date</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="275"/>
        <source>&lt;em&gt;No output.&lt;/em&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="281"/>
        <source>&lt;em&gt;No error.&lt;/em&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="287"/>
        <source>&lt;p&gt;&lt;strong&gt;Command:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Command could not be started&lt;/strong&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="289"/>
        <source>&lt;p&gt;&lt;strong&gt;Command:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Standard Output :&lt;/strong&gt;&lt;pre&gt;%2&lt;/pre&gt;&lt;strong&gt;Error Output :&lt;/strong&gt;&lt;pre&gt;%3&lt;/pre&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="291"/>
        <source>An error occurred while updating crontab.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="298"/>
        <source>Unable to open crontab file for writing</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="298"/>
        <source>The file %1 could not be opened.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CTDayOfMonth</name>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="22"/>
        <source>every day </source>
        <translation>каждый день </translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>1st</source>
        <translation>1го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>2nd</source>
        <translation>2го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>3rd</source>
        <translation>3го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>4th</source>
        <translation>4го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>5th</source>
        <translation>5го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>6th</source>
        <translation>6го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>7th</source>
        <translation>7го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>8th</source>
        <translation>8го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>9th</source>
        <translation>9го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>10th</source>
        <translation>10</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>11th</source>
        <translation>11го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>12th</source>
        <translation>12го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>13th</source>
        <translation>13го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>14th</source>
        <translation>14го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>15th</source>
        <translation>15го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>16th</source>
        <translation>16го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>17th</source>
        <translation>17го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>18th</source>
        <translation>18го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>19th</source>
        <translation>19го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>20th</source>
        <translation>20го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>21st</source>
        <translation>21го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>22nd</source>
        <translation>22го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>23rd</source>
        <translation>23го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>24th</source>
        <translation>24го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>25th</source>
        <translation>25го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>26th</source>
        <translation>26го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>27th</source>
        <translation>27го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>28th</source>
        <translation>28го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>29th</source>
        <translation>29го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>30th</source>
        <translation>30го</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>31st</source>
        <translation>31го</translation>
    </message>
</context>
<context>
    <name>CTDayOfWeek</name>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="43"/>
        <source>every day </source>
        <translation>каждый день </translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Mon</source>
        <translation>Пн</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Tue</source>
        <translation>Вт</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Wed</source>
        <translation>Ср</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Thu</source>
        <translation>Чт</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Fri</source>
        <translation>Пт</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Sat</source>
        <translation>Сб</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Sun</source>
        <translation>Вс</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Monday</source>
        <translation>Понедельник</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Tuesday</source>
        <translation>Вторник</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Wednesday</source>
        <translation>Среда</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Thursday</source>
        <translation>Четверг</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Friday</source>
        <translation>Пятница</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Saturday</source>
        <translation>Суббота</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Sunday</source>
        <translation>Воскресенье</translation>
    </message>
</context>
<context>
    <name>CTGlobalCron</name>
    <message>
        <location filename="../crontablib/ctGlobalCron.cpp" line="28"/>
        <source>All users</source>
        <translation>Все пользователи</translation>
    </message>
</context>
<context>
    <name>CTHelper</name>
    <message>
        <location filename="../crontablib/ctHelper.cpp" line="20"/>
        <source>No comment</source>
        <translation>Нет комментария</translation>
    </message>
</context>
<context>
    <name>CTHost</name>
    <message>
        <location filename="../crontablib/cthost.cpp" line="57"/>
        <source>You have been blocked from using Crontablib	                      by either the /etc/cron.allow file or the /etc/cron.deny file.	                      

Check the crontab man page for further details.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cthost.cpp" line="139"/>
        <source>User %1: %2</source>
        <comment>User login: errorMessage</comment>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CTMonth</name>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="22"/>
        <source>every month</source>
        <translation>каждый месяц</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>January</source>
        <translation>Января</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>February</source>
        <translation>Февраля</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>March</source>
        <translation>Марта</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>April</source>
        <translation>Апреля</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>May</source>
        <comment>May long</comment>
        <translation>Мая</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>June</source>
        <translation>Июня</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>July</source>
        <comment>July long</comment>
        <translation>Июля</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>August</source>
        <translation>Августа</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>September</source>
        <translation>Сентября</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>October</source>
        <translation>Октября</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>November</source>
        <translation>Ноября</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>December</source>
        <translation>Декабря</translation>
    </message>
</context>
<context>
    <name>CTSystemCron</name>
    <message>
        <location filename="../crontablib/ctSystemCron.cpp" line="45"/>
        <source>System Crontab</source>
        <translation>Системный Crontab</translation>
    </message>
</context>
<context>
    <name>CTTask</name>
    <message>
        <location filename="../crontablib/cttask.cpp" line="238"/>
        <source>at system startup</source>
        <translation>при запуске системы</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="245"/>
        <source>%1, %2</source>
        <comment>1:Time Description, 2:Date Description</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="249"/>
        <source>every %1</source>
        <comment>Every &apos;days of week&apos;</comment>
        <translation>каждые %1</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="253"/>
        <source>%1 of %2</source>
        <comment>&apos;Days of month&apos; of &apos;Months&apos;</comment>
        <translation>%1 %2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="264"/>
        <source>every day </source>
        <translation>каждый день </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="275"/>
        <source>%1 as well as %2</source>
        <comment>1:Day of month, 2:Day of week</comment>
        <translation>%1 при этом %2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="305"/>
        <source>%1:%2</source>
        <comment>1:Hour, 2:Minute</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="314"/>
        <source>, and </source>
        <translation>, и </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="316"/>
        <source> and </source>
        <translation> и </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="319"/>
        <source>, </source>
        <translation></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="325"/>
        <source>at %1</source>
        <comment>Hour::Minute list</comment>
        <translation>в %1</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="332"/>
        <source>Every minute</source>
        <comment>Every minute</comment>
        <translation>каждую минуту</translation>
    </message>
</context>
<context>
    <name>CTUnit</name>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="170"/>
        <source>,</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="171"/>
        <source> and </source>
        <translation> и </translation>
    </message>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="174"/>
        <source>, </source>
        <translation></translation>
    </message>
</context>
<context>
    <name>CTVariable</name>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="121"/>
        <source>Override default home folder.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="124"/>
        <source>Email output to specified account.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="127"/>
        <source>Override default shell.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="130"/>
        <source>Folders to search for program files.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="133"/>
        <source>Dynamic libraries location.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="136"/>
        <source>Local Variable</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CommandDialog</name>
    <message>
        <location filename="../src/commanddialog.ui" line="14"/>
        <source>Dialog</source>
        <translation>Диалог</translation>
    </message>
    <message>
        <location filename="../src/commanddialog.ui" line="24"/>
        <source>Description:</source>
        <translation>Описание:</translation>
    </message>
    <message>
        <location filename="../src/commanddialog.ui" line="31"/>
        <source>Command:</source>
        <translation>Команда:</translation>
    </message>
    <message>
        <location filename="../src/commanddialog.ui" line="38"/>
        <source>Run at</source>
        <translation>Запустить в</translation>
    </message>
    <message>
        <location filename="../src/commanddialog.ui" line="65"/>
        <source> hrs</source>
        <translation> час</translation>
    </message>
    <message>
        <location filename="../src/commanddialog.ui" line="78"/>
        <source> mins</source>
        <translation> мин</translation>
    </message>
    <message>
        <location filename="../src/commanddialog.ui" line="91"/>
        <source>Now</source>
        <translation>Сейчас</translation>
    </message>
    <message>
        <location filename="../src/commanddialog.ui" line="98"/>
        <source>Reset</source>
        <translation>Сброс</translation>
    </message>
    <message>
        <location filename="../src/commanddialog.ui" line="113"/>
        <source>Show OSD notification</source>
        <translation>Показать экранное оповещение</translation>
    </message>
    <message>
        <location filename="../src/commanddialog.cpp" line="37"/>
        <location filename="../src/commanddialog.cpp" line="38"/>
        <source>New Command</source>
        <translation>Новая команда</translation>
    </message>
    <message>
        <location filename="../src/commanddialog.cpp" line="63"/>
        <source>Command field should not be empty</source>
        <translation>Поле Команда не должно быть пустым</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="../src/mainwindow.ui" line="14"/>
        <source>Zeit</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="38"/>
        <source>&amp;Zeit</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="48"/>
        <source>He&amp;lp</source>
        <translation>По&amp;мощь</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="86"/>
        <source>&amp;About</source>
        <translation>&amp;О программе</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="102"/>
        <source>&amp;Quit</source>
        <translation>&amp;Выход</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="54"/>
        <source>&amp;Tools</source>
        <translation>&amp;Инструменты</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="61"/>
        <source>&amp;View</source>
        <translation>&amp;Вид</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="94"/>
        <source>&amp;Add Entry</source>
        <translation>&amp;Добавить элемент</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="110"/>
        <source>&amp;Delete Entry</source>
        <translation>&amp;Удалить элемент</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="113"/>
        <source>Delete Entry</source>
        <translation>Удалить элемент</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="121"/>
        <source>&amp;Modify Entry</source>
        <translation>&amp;Изменить элемент</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="197"/>
        <source>Refresh</source>
        <translation>Обновить</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="129"/>
        <source>&amp;Timer</source>
        <translation>&amp;Таймер</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="137"/>
        <source>&amp;Alarm</source>
        <translation>&amp;Будильник</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="151"/>
        <source>&amp;Periodic Tasks</source>
        <translation>&amp;Периодические задания</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="159"/>
        <source>&amp;Root Mode</source>
        <translation>&amp;Системный режим</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="167"/>
        <source>&amp;Environment Variables</source>
        <translation>Переменные &amp;окружения</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="178"/>
        <source>&amp;Nonperiodic Commands</source>
        <translation>&amp;Непериодические команды</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.ui" line="189"/>
        <source>&amp;System Mode</source>
        <translation>&amp;Системный режим</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="215"/>
        <source>New Task</source>
        <translation>Новое задание</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="222"/>
        <source>New Variable</source>
        <translation>Новая переменная</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="253"/>
        <source>Edit Variable</source>
        <translation>Изменить переменную</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="266"/>
        <source>Deleting Entry</source>
        <translation>Удалить элемент</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="266"/>
        <source>Delete entry?</source>
        <translation>Удалить элемент?</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="301"/>
        <source>Add Task</source>
        <translation>Новое Задание</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="303"/>
        <source>Delete Task</source>
        <translation>Удалить задание</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="310"/>
        <source>Add Variable</source>
        <translation>Новая Переменная</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="311"/>
        <source>Modify Variable</source>
        <translation>Изменить переменную</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="312"/>
        <source>Delete Variable</source>
        <translation>Удалить переменную</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="319"/>
        <source>Add Command</source>
        <translation>Новая Команда</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="320"/>
        <source>Modify Command</source>
        <translation>Изменить команду</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="321"/>
        <source>Delete Command</source>
        <translation>Удалить команду</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="302"/>
        <source>Modify Task</source>
        <translation>Изменить задание</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="243"/>
        <source>Edit Task</source>
        <translation>Изменить задание</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="../src/mainwindow.cpp" line="111"/>
        <source>Command: %1
</source>
        <translation>Команда: %1
</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="112"/>
        <source>Description</source>
        <translation>Описание</translation>
    </message>
    <message>
        <location filename="../src/mainwindow.cpp" line="114"/>
        <source>Runs </source>
        <comment>Runs at &apos;period described&apos;</comment>
        <translation>Выполняется </translation>
    </message>
</context>
<context>
    <name>TaskDialog</name>
    <message>
        <location filename="../src/taskdialog.ui" line="14"/>
        <source>Dialog</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="24"/>
        <source>Description:</source>
        <translation>Описание:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="31"/>
        <source>Command:</source>
        <translation>Команда:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="38"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;b&gt;Time &amp;amp; Date:&lt;/b&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;b&gt;Время и дата:&lt;/b&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="45"/>
        <source>Basic</source>
        <translation>Базовый</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="52"/>
        <source>Ad&amp;vanced</source>
        <translation>&amp;Расширенный</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="59"/>
        <source>Minute:</source>
        <translation>Минуты:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="66"/>
        <source>Hour:</source>
        <translation>Часы:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="73"/>
        <source>Day:</source>
        <translation>Дни:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="80"/>
        <source>Weekday:</source>
        <translation>Дни недели:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.ui" line="87"/>
        <source>Month:</source>
        <translation>Месяцы:</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="38"/>
        <source>Every minute</source>
        <translation>Каждую минуту</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="38"/>
        <source>Every hour</source>
        <translation>Каждый час</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="38"/>
        <source>Every day</source>
        <translation>Каждый день</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="39"/>
        <source>Every week</source>
        <translation>Каждую неделю</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="39"/>
        <source>Every month</source>
        <translation>Каждый месяц</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="41"/>
        <source>Valid input examples:&lt;br/&gt;&lt;b&gt;*&lt;/b&gt; – all elements are enabled&lt;br/&gt;&lt;b&gt;3&lt;/b&gt; – one element is enabled&lt;br/&gt;&lt;b&gt;1,2,5&lt;/b&gt; – sequence of three elements&lt;br/&gt;&lt;b&gt;2-7&lt;/b&gt; – range from 2 to 7&lt;br/&gt;&lt;b&gt;3-15/2&lt;/b&gt; – range from 3 to 15 with step 2&lt;br/&gt;&lt;b&gt;3-15,18,21&lt;/b&gt; – combination of the above</source>
        <translation>Примеры допустимого ввода:&lt;br/&gt;&lt;b&gt;*&lt;/b&gt; – все элементы включены&lt;br/&gt;&lt;b&gt;3&lt;/b&gt; – один элемент включен&lt;br/&gt;&lt;b&gt;1,2,5&lt;/b&gt; – последовательность трех элементов&lt;br/&gt;&lt;b&gt;2-7&lt;/b&gt; – диапазон от 2 до 7&lt;br/&gt;&lt;b&gt;3-15/2&lt;/b&gt; – диапазон от 3 до 15 с шагом 2&lt;br/&gt;&lt;b&gt;3-15,18,21&lt;/b&gt; – сочетание приведенного выше</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="72"/>
        <source>New Task</source>
        <translation>Новое задание</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="151"/>
        <source>Command field should not be empty</source>
        <translation>Поле Команда не должно быть пустым</translation>
    </message>
    <message>
        <location filename="../src/taskdialog.cpp" line="158"/>
        <source>Invalid input in </source>
        <translation>Недопустимый ввод в </translation>
    </message>
</context>
<context>
    <name>TimerDialog</name>
    <message>
        <location filename="../src/timerdialog.ui" line="14"/>
        <source>Dialog</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="20"/>
        <source>Description:</source>
        <translation>Описание:</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="34"/>
        <source>Player:</source>
        <translation>Плеер:</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="55"/>
        <source>Sound file:</source>
        <translation>Зв. файл:</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="76"/>
        <source>Run at</source>
        <translation>Запустить в</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="83"/>
        <source> hrs</source>
        <translation>час</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="96"/>
        <source> mins</source>
        <translation>мин</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="109"/>
        <source>Now</source>
        <translation>Сейчас</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="116"/>
        <source>Reset</source>
        <translation>Сброс</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.ui" line="123"/>
        <source>Show OSD notification</source>
        <translation>Показать экранное оповещение</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.cpp" line="38"/>
        <location filename="../src/timerdialog.cpp" line="40"/>
        <source>New Timer</source>
        <translation>Новый таймер</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.cpp" line="100"/>
        <source>Player field should not be empty</source>
        <translation>Поле Плеер не должно быть пустым</translation>
    </message>
    <message>
        <location filename="../src/timerdialog.cpp" line="104"/>
        <source>Soundfile field should not be empty</source>
        <translation>Поле Зв. файл не должно быть пустым</translation>
    </message>
</context>
<context>
    <name>VariableDialog</name>
    <message>
        <location filename="../src/variabledialog.ui" line="14"/>
        <source>Dialog</source>
        <translation>Диалог</translation>
    </message>
    <message>
        <location filename="../src/variabledialog.ui" line="24"/>
        <source>Variable:</source>
        <translation>Переменная:</translation>
    </message>
    <message>
        <location filename="../src/variabledialog.ui" line="31"/>
        <source>Value:</source>
        <translation>Значение:</translation>
    </message>
    <message>
        <location filename="../src/variabledialog.ui" line="38"/>
        <source>Comment:</source>
        <translation>Комментарий:</translation>
    </message>
    <message>
        <location filename="../src/variabledialog.cpp" line="48"/>
        <source>Variable field should not be empty</source>
        <translation>Поле Переменная не должно быть пустым</translation>
    </message>
    <message>
        <location filename="../src/variabledialog.cpp" line="52"/>
        <source>Invalid variable name</source>
        <translation>Недопустимое имя переменной</translation>
    </message>
</context>
</TS>
